"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, ArrowRight, Banknote, Boxes, CalendarClock, CircleDollarSign, FileChartColumn, PackagePlus, Pencil, Plus, Save, Trash2, TrendingUp, Users, Zap } from "lucide-react";
import { calculateEconomics, money, number } from "@/lib/economics";
import type { Project, ProjectCost, ProjectItem, RevenueModel, WorkspaceData } from "@/lib/types";

type Tab = "overview" | "inventory" | "costs" | "economics" | "financial";
const tabs:{id:Tab;label:string;icon:React.ElementType}[]=[
  {id:'overview',label:'Overview',icon:FileChartColumn},{id:'inventory',label:'Products & sourcing',icon:Boxes},{id:'costs',label:'Project costs',icon:Banknote},{id:'economics',label:'Customer economics',icon:TrendingUp},{id:'financial',label:'Financial model',icon:CircleDollarSign},
];
const productCategories=['Solar panels','Inverters','Racking','Cables','Electrical','Monitoring','Batteries','Transformers','Other'];
const productAvailability=['Available','Low stock','Backordered','Discontinued'];

export function ProjectWorkspace({projectId}:{projectId:string}){
  const[data,setData]=useState<WorkspaceData|null>(null);const[tab,setTab]=useState<Tab>('overview');const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[addItem,setAddItem]=useState(false);const[editingItem,setEditingItem]=useState<ProjectItem|null>(null);const[addCost,setAddCost]=useState(false);const[editingCost,setEditingCost]=useState<ProjectCost|null>(null);
  const load=()=>fetch(`/api/projects/${projectId}/workspace`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message));
  useEffect(()=>{ void load(); },[projectId]);
  const economics=useMemo(()=>data?calculateEconomics(data.project,data.items,data.costs,data.revenue):null,[data]);
  if(!data)return <div className="loading"><div>{error?<div className="error-banner">{error}</div>:<><div className="spinner"/>Loading project model…</>}</div></div>;
  function setProject<K extends keyof Project>(key:K,value:Project[K]){setData(d=>d?{...d,project:{...d.project,[key]:value}}:d)}
  function setRevenue<K extends keyof RevenueModel>(key:K,value:RevenueModel[K]){setData(d=>d?{...d,revenue:{...d.revenue,[key]:value}}:d)}
  async function saveProject(){setSaving(true);setError('');try{const r=await fetch(`/api/projects/${projectId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data!.project)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(v=>v?{...v,project:d.project}:v)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  async function saveRevenue(){setSaving(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/revenue`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data!.revenue)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(v=>v?{...v,revenue:d.revenue}:v)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  async function remove(kind:'items'|'costs',id:string){if(!confirm('Remove this line from the project?'))return;await fetch(`/api/${kind}/${id}`,{method:'DELETE'});load()}
  async function moveCost(id:string,cost_category:'Installation'|'Maintenance'){setError('');const response=await fetch(`/api/costs/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({cost_category})});const payload=await response.json();if(!response.ok){setError(payload.error||'Could not move this cost.');return}setData(current=>current?{...current,costs:current.costs.map(cost=>cost.id===id?{...cost,cost_category}:cost)}:current)}
  async function changeItemStatus(id:string,status:string){setData(current=>current?{...current,items:current.items.map(item=>item.id===id?{...item,status:status as ProjectItem['status']}:item)}:current);const response=await fetch(`/api/items/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!response.ok){const payload=await response.json();setError(payload.error);load()}}
  async function submitItem(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/projects/${projectId}/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setAddItem(false);load()}
  async function submitItemEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editingItem)return;const form=new FormData(e.currentTarget);const scope=String(form.get('edit_scope')||'project');form.delete('edit_scope');const r=scope==='catalog'?await fetch(`/api/products/${editingItem.product_id}`,{method:'PATCH',body:form}):await fetch(`/api/items/${editingItem.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const d=await r.json();if(!r.ok){setError(d.error);return}setEditingItem(null);load()}
  async function submitCost(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/projects/${projectId}/costs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setAddCost(false);load()}
  async function submitCostEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editingCost)return;const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/costs/${editingCost.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setEditingCost(null);load()}
  const e=economics!;
  return <>
    <Link href="/projects" style={{display:'inline-flex',alignItems:'center',gap:6,color:'#627169',fontSize:11,marginBottom:13}}><ArrowLeft size={14}/>Back to projects</Link>
    <section className="project-hero"><div><p className="eyebrow">{data.project.code} · {data.project.status}</p><h1>{data.project.name}</h1><p>{data.project.customer_name} · {data.project.location}</p></div><div style={{display:'flex',gap:30}}><div className="hero-stat"><span>System size</span><strong>{number(Number(data.project.capacity_kw),2)} kW</strong></div><div className="hero-stat"><span>Total modeled cost</span><strong>{money(e.totalProjectCost,true)}</strong></div></div></section>
    {error&&<div className="error-banner">{error}</div>}
    <div className="tabs">{tabs.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'tab active':'tab'} onClick={()=>setTab(id)}><span style={{display:'inline-flex',alignItems:'center',gap:7}}><Icon size={14}/>{label}</span></button>)}</div>

    {tab==='overview'&&<Overview data={data} e={e} setProject={setProject} save={saveProject} saving={saving}/>} 
    {tab==='inventory'&&<InventoryEditor data={data} e={e} add={()=>setAddItem(true)} edit={setEditingItem} remove={(id)=>remove('items',id)} changeStatus={changeItemStatus}/>}
    {tab==='costs'&&<CostsByCategory data={data} e={e} add={()=>setAddCost(true)} remove={(id)=>remove('costs',id)} move={moveCost} edit={setEditingCost}/>}
    {tab==='economics'&&<EconomicsView data={data} e={e} setProject={setProject} setRevenue={setRevenue} save={async()=>{await saveProject();await saveRevenue()}} saving={saving}/>}
    {tab==='financial'&&<FinancialModel data={data} e={e} setRevenue={setRevenue} save={saveRevenue} saving={saving}/>}

    {addItem&&<ItemModal data={data} close={()=>setAddItem(false)} submit={submitItem}/>} 
    {editingItem&&<ItemModal data={data} item={editingItem} close={()=>setEditingItem(null)} submit={submitItemEdit}/>}
    {addCost&&<CostCategoryModal catalog={data.costCatalog} close={()=>setAddCost(false)} submit={submitCost}/>}
    {editingCost&&<CostCategoryModal catalog={data.costCatalog} cost={editingCost} close={()=>setEditingCost(null)} submit={submitCostEdit}/>}
  </>;
}

function Overview({data,e,setProject,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setProject:<K extends keyof Project>(k:K,v:Project[K])=>void;save:()=>void;saving:boolean}){
  const installationCosts=data.costs.filter(cost=>(cost.cost_category||'Installation')==='Installation').reduce((sum,cost)=>sum+Number(cost.amount),0);
  const maintenanceCosts=data.costs.filter(cost=>cost.cost_category==='Maintenance').reduce((sum,cost)=>sum+Number(cost.amount),0);
  const costChart=[{name:'Installation',value:e.equipmentCost+installationCosts},{name:'Maintenance',value:maintenanceCosts}];
  return <><div className="metric-grid"><Metric label="Project investment" value={money(e.totalProjectCost,true)} note={`${money(e.equipmentCost,true)} Materials`} icon={Banknote} hero/><Metric label="Year-one generation" value={`${number(e.yearOneGeneration/1000,1)} MWh`} note={`${number(Number(data.project.specific_yield_kwh_kw))} kWh/kW yield`} icon={Zap}/><Metric label="Customer net savings" value={money(e.customerNetSavings,true)} note="Year one after customer fee" icon={CircleDollarSign}/><Metric label="Platform payback" value={e.projectPaybackYears?`${e.projectPaybackYears} years`:'Beyond term'} note={`${number(e.roiPct,1)}% contract ROI`} icon={TrendingUp}/></div>
    <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Project assumptions</h2><p>Changes recalculate the model immediately</p></div><button className="button primary small" onClick={save} disabled={saving}><Save size={13}/>{saving?'Saving…':'Save assumptions'}</button></div><div className="assumption-grid"><Assumption label="System capacity (kW)" value={data.project.capacity_kw} onChange={v=>setProject('capacity_kw',v)}/><Assumption label="Annual customer load (kWh)" value={data.project.annual_usage_kwh} onChange={v=>setProject('annual_usage_kwh',v)}/><Assumption label="Electricity rate (MXN/kWh)" value={data.project.electricity_rate} step="0.01" onChange={v=>setProject('electricity_rate',v)}/><Assumption label="Specific yield (kWh/kW)" value={data.project.specific_yield_kwh_kw} onChange={v=>setProject('specific_yield_kwh_kw',v)}/><Assumption label="Utility escalation (%)" value={data.project.utility_escalation_pct} step="0.1" onChange={v=>setProject('utility_escalation_pct',v)}/><Assumption label="Module degradation (%)" value={data.project.degradation_pct} step="0.05" onChange={v=>setProject('degradation_pct',v)}/></div></section>
    <section className="card"><div className="card-header"><div><h2>Capital stack</h2><p>Current project cost composition</p></div></div><div className="chart-wrap" style={{height:250}}><ResponsiveContainer width="100%" height="100%"><BarChart data={costChart} layout="vertical" margin={{left:8,right:20}}><CartesianGrid stroke="#e8ede9" horizontal={false}/><XAxis type="number" tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" tick={{fontSize:10}} width={70} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="value" radius={[0,7,7,0]}>{costChart.map((_,i)=><Cell key={i} fill={i===0?'#143d2d':'#f4c75d'}/>)}</Bar></BarChart></ResponsiveContainer></div></section></div></>;
}

function Inventory({data,e,add,remove}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void}){
  return <section className="card"><div className="card-header"><div><h2>Bill of materials & sourcing</h2><p>{data.items.length} line items · {money(e.equipmentCost,true)} total equipment</p></div><button className="button primary small" onClick={add}><PackagePlus size={14}/>Add from catalog</button></div>{data.items.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Qty.</th><th>Unit cost</th><th>Extended</th><th>Supplier</th><th>Delivery</th><th>Status</th><th></th></tr></thead><tbody>{data.items.map(i=><tr key={i.id}><td><div className="table-title"><div><span className="project-code">{i.product_category} · {i.product_sku}</span><strong>{i.product_name}</strong><span>{i.product_model}</span></div></div></td><td>{number(Number(i.quantity),2)}</td><td>{money(Number(i.unit_price))}</td><td><strong>{money(Number(i.quantity)*Number(i.unit_price),true)}</strong></td><td>{i.supplier||'—'}</td><td>{i.expected_delivery?new Date(i.expected_delivery+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—'}</td><td><span className={`status ${i.status.replace(' ','-')}`}>{i.status}</span></td><td><button className="button ghost small" onClick={()=>remove(i.id)} aria-label="Remove"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty icon={Boxes} title="No products assigned" text="Choose products from the catalog to build this project's bill of materials."/>}</section>;
}

function InventoryEditor({data,e,add,edit,remove,changeStatus}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;edit:(item:ProjectItem)=>void;remove:(id:string)=>void;changeStatus:(id:string,status:string)=>void}){
  const statuses=['Planned','Quoted','Ordered','In transit','Delivered','Installed'];
  return <section className="card">
    <div className="card-header"><div><h2>Bill of materials & sourcing</h2><p>{data.items.length} sourced product lines with delivery and fulfillment tracking</p></div><button className="button primary small" onClick={add}><PackagePlus size={14}/>Add from catalog</button></div>
    {data.items.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Qty.</th><th>Unit cost</th><th>Extended</th><th>Supplier</th><th>Delivery</th><th>Status</th><th></th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}>
      <td><div className="table-title"><div><span className="project-code">{item.product_category} · {item.product_sku}</span><strong>{item.product_name}</strong><span>{item.product_model}</span>{item.notes&&<span className="item-note">{item.notes}</span>}</div></div></td>
      <td>{number(Number(item.quantity),2)}</td><td>{money(Number(item.unit_price))}</td><td><strong>{money(Number(item.quantity)*Number(item.unit_price),true)}</strong></td><td>{item.supplier||'—'}</td>
      <td>{formatWorkspaceDate(item.expected_delivery)}</td>
      <td><select className="inline-select" aria-label={`Sourcing status for ${item.product_name}`} value={item.status} onChange={event=>changeStatus(item.id,event.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></td>
      <td><div className="cost-row-actions"><button className="button ghost small" onClick={()=>edit(item)} aria-label={`Edit ${item.product_name}`} title="Edit sourcing line"><Pencil size={13}/></button><button className="button ghost small" onClick={()=>remove(item.id)} aria-label={`Remove ${item.product_name}`}><Trash2 size={14}/></button></div></td>
    </tr>)}</tbody><tfoot><tr className="bom-total-row"><td colSpan={3}><strong>Total bill of materials</strong></td><td><strong>{money(e.equipmentCost)}</strong><span>total cost</span></td><td colSpan={4}></td></tr></tfoot></table></div>:<Empty icon={Boxes} title="No products assigned" text="Choose products from the catalog to build this project's bill of materials."/>}
  </section>;
}

function CostsByCategory({data,e,add,remove,move,edit}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void;move:(id:string,category:'Installation'|'Maintenance')=>void;edit:(cost:ProjectCost)=>void}){
  const installation=data.costs.filter(cost=>(cost.cost_category||'Installation')==='Installation');
  const maintenance=data.costs.filter(cost=>cost.cost_category==='Maintenance');
  const installationServicesTotal=installation.reduce((sum,cost)=>sum+Number(cost.amount),0);
  const installationTotal=e.equipmentCost+installationServicesTotal;
  const maintenanceTotal=maintenance.reduce((sum,cost)=>sum+Number(cost.amount),0);
  return <>
    <div className="cost-category-heading"><div><h2>Installation & maintenance costs</h2><p>Separate upfront delivery costs from ongoing asset-care allowances.</p></div><button className="button primary small" onClick={add}><Plus size={14}/>Add cost</button></div>
    <div className="cost-category-grid">
      <CostBucket title="Installation" description="Materials, engineering, permits, freight and construction" icon={Banknote} costs={installation} total={installationTotal} materialsTotal={e.equipmentCost} moveTarget="Maintenance" remove={remove} move={move} edit={edit}/>
      <CostBucket title="Maintenance" description="Monitoring, cleaning, preventive and corrective care" icon={CalendarClock} costs={maintenance} total={maintenanceTotal} moveTarget="Installation" remove={remove} move={move} edit={edit}/>
    </div>
    <section className="card cost-total-card">
      <div className="card-header"><div><h2>Project cost statement</h2><p>Installation, maintenance, and fully loaded project cost</p></div><span className="statement-currency">MXN</span></div>
      <div className="pnl-statement">
        <div className="pnl-row"><span>Installation incl. Materials</span><strong>{money(installationTotal)}</strong></div>
        <div className="pnl-row"><span>Maintenance</span><strong>{money(maintenanceTotal)}</strong></div>
        <div className="pnl-row total"><span>Total project cost</span><strong>{money(e.totalProjectCost)}</strong></div>
      </div>
    </section>
  </>;
}

function CostBucket({title,description,icon:Icon,costs,total,materialsTotal,moveTarget,remove,move,edit}:{title:string;description:string;icon:React.ElementType;costs:ProjectCost[];total:number;materialsTotal?:number;moveTarget:'Installation'|'Maintenance';remove:(id:string)=>void;move:(id:string,category:'Installation'|'Maintenance')=>void;edit:(cost:ProjectCost)=>void}){
  const hasMaterials=materialsTotal!==undefined;
  return <section className="card cost-bucket"><div className="card-header"><div className="cost-bucket-title"><span className="metric-icon"><Icon size={16}/></span><div><h2>{title}</h2><p>{description}</p></div></div><strong>{money(total)}</strong></div>
    {(hasMaterials||costs.length)?<div className="table-wrap"><table className="data-table cost-table"><thead><tr><th>Cost & note</th><th>Amount</th><th></th></tr></thead><tbody>{hasMaterials&&<tr className="materials-cost-row"><td><strong>Materials</strong><span className="cost-note">Automatically tallied from Products & sourcing</span></td><td><strong>{money(materialsTotal)}</strong></td><td></td></tr>}{costs.map(cost=><tr key={cost.id}><td><strong>{cost.label}</strong>{cost.notes&&<span className="cost-note">{cost.notes}</span>}</td><td><strong>{money(Number(cost.amount))}</strong></td><td><div className="cost-row-actions"><button className="button ghost small" onClick={()=>edit(cost)} aria-label={`Edit ${cost.label}`} title="Edit cost"><Pencil size={13}/></button><button className="button ghost small move-cost-button" onClick={()=>move(cost.id,moveTarget)} aria-label={`Move ${cost.label} to ${moveTarget}`} title={`Move to ${moveTarget}`}>{moveTarget==='Maintenance'?<ArrowRight size={14}/>:<ArrowLeft size={14}/>}</button><button className="button ghost small" onClick={()=>remove(cost.id)} aria-label={`Remove ${cost.label}`}><Trash2 size={14}/></button></div></td></tr>)}</tbody><tfoot><tr><td><strong>{title} subtotal</strong></td><td><strong>{money(total)}</strong></td><td></td></tr></tfoot></table></div>:<Empty icon={Icon} title={`No ${title.toLowerCase()} costs`} text={`Add the first ${title.toLowerCase()} cost to this project.`}/>}</section>;
}

function EconomicsView({data,e,setProject,setRevenue,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setProject:<K extends keyof Project>(k:K,v:Project[K])=>void;setRevenue:<K extends keyof RevenueModel>(k:K,v:RevenueModel[K])=>void;save:()=>void;saving:boolean}){
  const previousBill=Number(data.revenue.previous_cfe_monthly_bill||0);
  const residualBill=Number(data.revenue.residual_cfe_monthly_bill||0);
  const proposedBill=Number(data.revenue.monthly_customer_fee||0);
  const estimatedCfeReduction=Math.max(0,previousBill-residualBill);
  return <><div className="metric-grid"><Metric label="Year-one bill avoided" value={money(e.yearOneBillSavings,true)} note={previousBill>0?'From saved CFE bill baseline':`${number(e.yearOneGeneration/1000,1)} MWh generated`} icon={Zap} hero/><Metric label="Customer annual fee" value={money(e.yearOneRevenue,true)} note={money(proposedBill)+' monthly'} icon={CircleDollarSign}/><Metric label="Customer saves in year 1" value={money(e.customerNetSavings,true)} note={previousBill>0?`${number(e.customerDiscountPct,1)}% below the prior CFE bill`:'Enter the prior CFE bill to calculate discount'} icon={Users}/><Metric label="Customer lifetime savings" value={money(e.customerLifetimeSavings,true)} note={`${data.revenue.contract_years}-year contract`} icon={TrendingUp}/></div>
    <section className="card revenue-builder-card">
      <div className="card-header"><div><h2>Monthly revenue & CFE bill</h2><p>Build the customer proposal from their prior bill, expected CFE minimum, and your monthly charge.</p></div><button className="button primary small" onClick={save} disabled={saving}><Save size={13}/>{saving?'Saving…':'Save revenue model'}</button></div>
      <div className="revenue-builder-grid">
        <div className="revenue-inputs">
          <Assumption label="Previous monthly CFE bill (MXN)" value={previousBill} onChange={v=>setRevenue('previous_cfe_monthly_bill',Math.max(0,v))}/>
          <Assumption label="Estimated CFE minimum after solar (MXN)" value={residualBill} onChange={v=>setRevenue('residual_cfe_monthly_bill',Math.max(0,v))}/>
          <Assumption label="Proposed Soluziomex monthly bill (MXN)" value={proposedBill} onChange={v=>setRevenue('monthly_customer_fee',Math.max(0,v))}/>
        </div>
        <div className="monthly-bill-statement">
          <div className="monthly-statement-head"><div><span>Customer proposal</span><strong>Monthly bill breakdown</strong></div><small>MXN / month</small></div>
          <div className="monthly-statement-row"><span>Previous CFE bill</span><strong>{money(previousBill)}</strong></div>
          <div className="monthly-statement-row reduction"><span>Estimated CFE reduction</span><strong>− {money(estimatedCfeReduction)}</strong></div>
          <div className="monthly-statement-row"><span>Residual CFE minimum</span><strong>{money(residualBill)}</strong></div>
          <div className="monthly-statement-row"><span>Proposed Soluziomex bill</span><strong>{money(proposedBill)}</strong></div>
          <div className="monthly-statement-row subtotal"><span>Total post-solar monthly outlay</span><strong>{money(e.monthlyTotalCustomerOutlay)}</strong></div>
          <div className={`monthly-statement-row savings ${e.monthlyCustomerSavings<0?'negative':''}`}><span>Client monthly savings</span><strong>{money(e.monthlyCustomerSavings)} · {number(e.customerDiscountPct,1)}%</strong></div>
          <div className="monthly-revenue-total"><span>Estimated monthly revenue</span><strong>{money(proposedBill)}</strong></div>
        </div>
      </div>
    </section>
    <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Customer value proposition</h2><p>Utility bill avoided, customer fee, and net savings</p></div></div><div className="chart-wrap" style={{height:360}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={e.series} margin={{top:5,right:20,left:8}}><CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tickFormatter={v=>`Y${v}`} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>`Year ${v}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/><Legend wrapperStyle={{fontSize:10}}/><Area type="monotone" dataKey="billSavings" name="Utility bill avoided" stroke="#5d83be" fill="#dfe9f7" strokeWidth={2}/><Area type="monotone" dataKey="customerFee" name="Customer fee" stroke="#143d2d" fill="#dcebe3" strokeWidth={2}/><Line type="monotone" dataKey="customerNetSavings" name="Customer net savings" stroke="#e2a82d" strokeWidth={3} dot={false}/></AreaChart></ResponsiveContainer></div></section>
    <section className="card"><div className="card-header"><div><h2>Commercial assumptions</h2><p>Adjust and see results immediately</p></div><button className="button primary small" onClick={save} disabled={saving}><Save size={13}/>{saving?'Saving…':'Save model'}</button></div><div className="assumption-grid" style={{gridTemplateColumns:'1fr 1fr'}}><Assumption label="Contract term (years)" value={data.revenue.contract_years} onChange={v=>setRevenue('contract_years',v)}/><Assumption label="Electricity rate (MXN/kWh)" value={data.project.electricity_rate} step="0.01" onChange={v=>setProject('electricity_rate',v)}/><Assumption label="Utility escalation (%)" value={data.project.utility_escalation_pct} step="0.1" onChange={v=>setProject('utility_escalation_pct',v)}/><Assumption label="Annual fee escalation (%)" value={data.revenue.annual_fee_escalation_pct} step="0.1" onChange={v=>setRevenue('annual_fee_escalation_pct',v)}/><Assumption label="Discount rate (%)" value={data.revenue.discount_rate_pct} step="0.1" onChange={v=>setRevenue('discount_rate_pct',v)}/></div></section></div></>;
}

function BreakevenChart({e}:{e:ReturnType<typeof calculateEconomics>}){
  const payback=e.projectPaybackYears;
  const series=[
    {year:0,cumulative:-e.totalProjectCost,negative:-e.totalProjectCost,positive:null as number|null},
    ...e.series.map(point=>({year:point.year,cumulative:point.cumulativePlatform,negative:point.cumulativePlatform<=0?point.cumulativePlatform:null,positive:point.cumulativePlatform>=0?point.cumulativePlatform:null})),
  ];
  if(payback!==null&&!Number.isInteger(payback))series.push({year:payback,cumulative:0,negative:0,positive:0});
  series.sort((a,b)=>a.year-b.year);
  const wholeYears=payback===null?0:Math.floor(payback);
  const months=payback===null?0:Math.round((payback-wholeYears)*12);
  const paybackLabel=payback===null?'Beyond contract term':`${wholeYears} yr${wholeYears===1?'':'s'}${months?` ${months} mo`:''}`;
  return <section className="card breakeven-card">
    <div className="card-header"><div><h2>Project break-even</h2><p>Cumulative Soluziomex cash flow after the full upfront project investment</p></div><span className={`status ${payback!==null?'Operating':''}`}>{payback!==null?`Break-even · year ${number(payback,1)}`:'No break-even in term'}</span></div>
    <div className="breakeven-layout">
      <div className="breakeven-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{top:30,right:24,left:12,bottom:8}}>
        <defs><linearGradient id="lossArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#dc6158" stopOpacity={.16}/><stop offset="100%" stopColor="#dc6158" stopOpacity={.48}/></linearGradient><linearGradient id="profitArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3a9a68" stopOpacity={.36}/><stop offset="100%" stopColor="#3a9a68" stopOpacity={.08}/></linearGradient></defs>
        <CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis type="number" dataKey="year" domain={[0,'dataMax']} tickFormatter={value=>`Y${value}`} tick={{fontSize:9,fill:'#738078'}} axisLine={false} tickLine={false}/><YAxis tickFormatter={value=>money(value,true)} tick={{fontSize:9,fill:'#738078'}} axisLine={false} tickLine={false}/><Tooltip formatter={value=>money(Number(value))} labelFormatter={value=>Number(value)===0?'Initial investment':`Year ${number(Number(value),1)}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/>
        <ReferenceLine y={0} stroke="#293b33" strokeWidth={1.5} label={{value:'CASH BREAK-EVEN',position:'insideTopLeft',fill:'#53635b',fontSize:9}}/>
        {payback!==null&&<ReferenceLine x={payback} stroke="#3a9a68" strokeDasharray="4 4" label={{value:`PAYBACK ${number(payback,1)} YRS`,position:'top',fill:'#27774f',fontSize:10,fontWeight:700}}/>}
        <Area type="linear" dataKey="negative" name="Capital not yet recovered" stroke="#cf5148" strokeWidth={3} fill="url(#lossArea)" connectNulls={false}/><Area type="linear" dataKey="positive" name="Cumulative profit" stroke="#2d895c" strokeWidth={3} fill="url(#profitArea)" connectNulls={false}/>
      </AreaChart></ResponsiveContainer></div>
      <aside className="breakeven-summary"><p className="eyebrow">Capital recovery</p><span className="breakeven-label">Estimated payback</span><strong className="breakeven-value">{paybackLabel}</strong><span className="breakeven-month">{payback!==null?`Approximately month ${Math.round(payback*12)}`:'Increase the fee or reduce project cost'}</span><div className="breakeven-key"><div><i className="loss-dot"/><span>Red</span><strong>Recovering {money(e.totalProjectCost,true)} investment</strong></div><div><i className="profit-dot"/><span>Green</span><strong>Positive cumulative project cash</strong></div></div><div className="breakeven-stats"><div><span>Year-one platform cash</span><strong>{money(e.platformYearOne,true)}</strong></div><div><span>Contract ROI</span><strong>{number(e.roiPct,1)}%</strong></div></div></aside>
    </div>
  </section>;
}

function FinancialModel({data,e,setRevenue,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setRevenue:<K extends keyof RevenueModel>(k:K,v:RevenueModel[K])=>void;save:()=>void;saving:boolean}){
  const total=Number(data.revenue.installer_share_pct)+Number(data.revenue.maintenance_reserve_pct)+Number(data.revenue.platform_share_pct);
  const payback=e.projectPaybackYears===null?'Beyond contract':`${number(e.projectPaybackYears,1)} years`;
  return <div className="financial-model"><div className="metric-grid"><Metric label="Project investment" value={money(e.totalProjectCost,true)} note="Full upfront capital requirement" icon={Banknote} hero/><Metric label="Estimated payback" value={payback} note={e.projectPaybackYears===null?'No break-even in current term':`Approximately month ${Math.round(e.projectPaybackYears*12)}`} icon={TrendingUp}/><Metric label="Contract ROI" value={`${number(e.roiPct,1)}%`} note={`${data.revenue.contract_years}-year modeled return`} icon={CircleDollarSign}/><Metric label="Platform NPV" value={money(e.npv,true)} note={`${data.revenue.discount_rate_pct}% discount rate`} icon={FileChartColumn}/></div>
    <BreakevenChart e={e}/>
    <div className="section-grid financial-split-grid"><section className="card"><div className="card-header"><div><h2>Annual stakeholder cash flow</h2><p>How customer revenue is distributed through the contract</p></div></div><div className="chart-wrap" style={{height:360}}><ResponsiveContainer width="100%" height="100%"><BarChart data={e.series} margin={{top:5,right:20,left:10}}><CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tickFormatter={v=>`Y${v}`} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>`Year ${v}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/><Legend wrapperStyle={{fontSize:10}}/><Bar dataKey="platform" name="Soluziomex" stackId="a" fill="#143d2d"/><Bar dataKey="maintenance" name="Maintenance reserve" stackId="a" fill="#77aa91"/><Bar dataKey="installer" name="Installer" stackId="a" fill="#f4c75d" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>
    <section className="card"><div className="card-header"><div><h2>Revenue allocation model</h2><p>Design the long-term installer, maintenance, and platform split</p></div><button className="button primary small" onClick={save} disabled={saving||Math.abs(total-100)>.001}><Save size={13}/>{saving?'Saving…':'Save financial model'}</button></div><div className="split-bar"><span style={{width:`${data.revenue.installer_share_pct}%`}}/><span style={{width:`${data.revenue.maintenance_reserve_pct}%`}}/><span style={{width:`${data.revenue.platform_share_pct}%`}}/></div><div className="legend"><div>Installer<strong>{data.revenue.installer_share_pct}%</strong></div><div>Maintenance<strong>{data.revenue.maintenance_reserve_pct}%</strong></div><div>Soluziomex<strong>{data.revenue.platform_share_pct}%</strong></div></div><div className="assumption-grid" style={{gridTemplateColumns:'1fr 1fr'}}><Assumption label="Installer share (%)" value={data.revenue.installer_share_pct} step="0.5" onChange={v=>setRevenue('installer_share_pct',v)}/><Assumption label="Maintenance reserve (%)" value={data.revenue.maintenance_reserve_pct} step="0.5" onChange={v=>setRevenue('maintenance_reserve_pct',v)}/><Assumption label="Soluziomex share (%)" value={data.revenue.platform_share_pct} step="0.5" onChange={v=>setRevenue('platform_share_pct',v)}/><Assumption label="Monthly customer fee (MXN)" value={data.revenue.monthly_customer_fee} onChange={v=>setRevenue('monthly_customer_fee',v)}/></div><div style={{margin:'0 18px 18px',padding:11,borderRadius:9,background:Math.abs(total-100)<.001?'#eaf5ee':'#fff1ef',color:Math.abs(total-100)<.001?'#397255':'#a64840',fontSize:10,fontWeight:700}}>Total allocation: {number(total,1)}% {Math.abs(total-100)<.001?'· ready to save':'· shares must equal 100%'}</div></section></div>
    <section className="card" style={{marginTop:18}}><div className="card-header"><div><h2>Stakeholder outcomes</h2><p>Nominal distributions over the full {data.revenue.contract_years}-year contract</p></div></div><div className="mini-metrics" style={{gridTemplateColumns:'repeat(4,1fr)'}}><div className="mini-metric"><span>Total customer fees</span><strong>{money(e.contractRevenue,true)}</strong></div><div className="mini-metric"><span>Installer lifetime income</span><strong>{money(e.contractRevenue*Number(data.revenue.installer_share_pct)/100,true)}</strong></div><div className="mini-metric"><span>Maintenance funded</span><strong>{money(e.contractRevenue*Number(data.revenue.maintenance_reserve_pct)/100,true)}</strong></div><div className="mini-metric"><span>Soluziomex gross cash</span><strong>{money(e.contractPlatformCash,true)}</strong></div></div></section></div>;
}

function Metric({label,value,note,icon:Icon,hero=false}:{label:string;value:string;note:string;icon:React.ElementType;hero?:boolean}){return <div className={`metric-card ${hero?'hero':''}`}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon size={16}/></span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>}
function Assumption({label,value,onChange,step='1'}:{label:string;value:string|number;onChange:(v:number)=>void;step?:string}){return <div className="assumption"><label>{label}</label><input type="number" step={step} value={Number(value)} onChange={ev=>onChange(Number(ev.target.value))}/></div>}
function Empty({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="empty-state"><Icon size={30}/><h3>{title}</h3><p>{text}</p></div>}

function ItemModal({data,close,submit,item}:{data:WorkspaceData;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void;item?:ProjectItem}){
  const[selected,setSelected]=useState(item?.product_id||data.products[0]?.id||'');const[scope,setScope]=useState<'project'|'catalog'>('project');const product=data.products.find(p=>p.id===selected);
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Project sourcing</p><h2>{item?'What should this edit update?':'Add product to bill of materials'}</h2></div><button type="button" className="button ghost small" onClick={close}>×</button></div><div className="modal-body">{item&&<><input type="hidden" name="edit_scope" value={scope}/><div className="edit-scope-grid"><button type="button" className={`edit-scope-option ${scope==='project'?'active':''}`} onClick={()=>setScope('project')}><strong>This project only</strong><span>Quantity, quoted price, supplier, delivery, status, and notes for this project.</span></button><button type="button" className={`edit-scope-option catalog ${scope==='catalog'?'active':''}`} onClick={()=>setScope('catalog')}><strong>Master product catalog</strong><span>Reusable product details shown everywhere this catalog item is used.</span></button></div><div className={`scope-notice ${scope}`}><strong>{scope==='project'?'Project-specific edit':'Catalog-wide edit'}</strong><span>{scope==='project'?`Changes stay inside ${data.project.name}.`:'Name, category, SKU, model, and other catalog details update across projects. Existing project quantities and quoted prices stay unchanged.'}</span></div></>}
      <div className="form-grid" key={item?scope:'new'}>{item?<div className="form-field full"><label>Selected product</label><div className="selected-product-summary"><strong>{item.product_name}</strong><span>{item.product_category} · {item.product_sku} · {item.product_model}</span></div></div>:<div className="form-field full"><label>Catalog product</label><select name="product_id" value={selected} onChange={e=>setSelected(e.target.value)}>{data.products.map(p=><option key={p.id} value={p.id}>{p.category} · {p.name} · {money(Number(p.unit_cost))}</option>)}</select></div>}
        {item&&scope==='catalog'&&product?<><Field name="sku" label="SKU" defaultValue={product.sku} required/><Field name="name" label="Product name" defaultValue={product.name} required/><div className="form-field"><label>Category</label><select name="category" defaultValue={product.category}>{productCategories.map(category=><option key={category}>{category}</option>)}</select></div><Field name="manufacturer" label="Manufacturer" defaultValue={product.manufacturer}/><Field name="model" label="Model" defaultValue={product.model}/><Field name="unit_cost" label="Catalog unit price (MXN)" type="number" min="0" step="0.01" defaultValue={product.unit_cost} required/><div className="form-field"><label>Availability</label><select name="status" defaultValue={product.status}>{productAvailability.map(status=><option key={status}>{status}</option>)}</select></div><div className="form-field full"><label>Source link</label><input name="source_url" defaultValue={product.source_url} placeholder="supplier.com/product or full URL"/><span className="form-help">Where this catalog product was found or purchased.</span></div><div className="form-field full"><label>Catalog description</label><textarea name="description" defaultValue={product.description} placeholder="Technical notes, warranty, certifications…"/></div></>:<>{(!item||scope==='project')&&<><Field name="quantity" label="Quantity" type="number" min="0.01" step="0.01" defaultValue={item?.quantity||1} required/><Field key={item?.id||product?.id} name="unit_price" label="Project unit price (MXN)" type="number" min="0" step="0.01" defaultValue={item?.unit_price??product?.unit_cost??0} required/><Field name="supplier" label="Supplier" placeholder="Supplier name" defaultValue={item?.supplier}/><Field name="expected_delivery" label="Expected delivery" type="date" defaultValue={workspaceDateInput(item?.expected_delivery)}/><div className="form-field"><label>Status</label><select name="status" defaultValue={item?.status||'Planned'}>{['Planned','Quoted','Ordered','In transit','Delivered','Installed'].map(status=><option key={status}>{status}</option>)}</select></div><div className="form-field full"><label>Project sourcing notes</label><textarea name="notes" defaultValue={item?.notes} placeholder="Quote, logistics, delivery, or project-specific notes…"/></div></>}</>}
      </div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">{item?(scope==='catalog'?'Update catalog product':'Save project changes'):'Add product'}</button></div></form></div>;
}
function CostCategoryModal({close,submit,cost,catalog}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void;cost?:ProjectCost;catalog:WorkspaceData['costCatalog']}){const[category,setCategory]=useState<'Installation'|'Maintenance'>(cost?.cost_category||'Installation');const[templateId,setTemplateId]=useState('');const template=catalog.find(entry=>entry.id===templateId);return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Project budget</p><h2>{cost?'Edit project cost':'Add a project cost'}</h2></div><button type="button" className="button ghost small" onClick={close}>×</button></div><div className="modal-body"><div className="form-grid">{!cost&&<div className="form-field full"><label>Cost catalog template</label><select value={templateId} onChange={event=>setTemplateId(event.target.value)}><option value="">Custom cost</option>{catalog.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><span className="form-help">Prefills the name and description. Category and amount stay specific to this project.</span></div>}<div className="form-field"><label>Cost category</label><select name="cost_category" value={category} onChange={event=>setCategory(event.target.value as 'Installation'|'Maintenance')}><option>Installation</option><option>Maintenance</option></select></div><Field key={`label-${templateId}`} name="label" label="Cost name" placeholder={category==='Installation'?'Mechanical installation labor':'Annual preventive maintenance'} defaultValue={cost?.label||template?.name} required/><Field name="amount" label="Amount (MXN)" type="number" min="0" step="0.01" defaultValue={cost?.amount} required/><div className="form-field full" key={`notes-${templateId}`}><label>Cost note</label><textarea name="notes" defaultValue={cost?.notes||template?.description} placeholder="Add a note specific to this cost, such as quote details, assumptions, frequency, or exclusions…"/></div></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">{cost?'Save changes':`Add ${category.toLowerCase()} cost`}</button></div></form></div>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...rest}=props;return <div className="form-field"><label>{label}</label><input {...rest}/></div>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <div className="form-field"><label>{label}</label><select name={name}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function workspaceDateInput(value:unknown){if(typeof value!=='string')return'';const iso=value.match(/^\d{4}-\d{2}-\d{2}/)?.[0]||'';if(!iso)return'';const parsed=new Date(`${iso}T00:00:00Z`);return Number.isNaN(parsed.getTime())?'':iso}
function formatWorkspaceDate(value:unknown){const iso=workspaceDateInput(value);if(!iso)return'—';return new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-US',{timeZone:'UTC',month:'short',day:'numeric'})}
