"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, Banknote, Boxes, CalendarClock, CircleDollarSign, FileChartColumn, Handshake, PackagePlus, Plus, Save, Trash2, TrendingUp, Users, Zap } from "lucide-react";
import { calculateEconomics, money, number } from "@/lib/economics";
import type { Project, ProjectCost, ProjectItem, RevenueModel, WorkspaceData } from "@/lib/types";

type Tab = "overview" | "inventory" | "costs" | "economics" | "sharing";
const tabs:{id:Tab;label:string;icon:React.ElementType}[]=[
  {id:'overview',label:'Overview',icon:FileChartColumn},{id:'inventory',label:'Products & sourcing',icon:Boxes},{id:'costs',label:'Project costs',icon:Banknote},{id:'economics',label:'Customer economics',icon:TrendingUp},{id:'sharing',label:'Revenue sharing',icon:Handshake},
];

export function ProjectWorkspace({projectId}:{projectId:string}){
  const[data,setData]=useState<WorkspaceData|null>(null);const[tab,setTab]=useState<Tab>('overview');const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[addItem,setAddItem]=useState(false);const[addCost,setAddCost]=useState(false);
  const load=()=>fetch(`/api/projects/${projectId}/workspace`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message));
  useEffect(()=>{ void load(); },[projectId]);
  const economics=useMemo(()=>data?calculateEconomics(data.project,data.items,data.costs,data.revenue):null,[data]);
  if(!data)return <div className="loading"><div>{error?<div className="error-banner">{error}</div>:<><div className="spinner"/>Loading project model…</>}</div></div>;
  function setProject<K extends keyof Project>(key:K,value:Project[K]){setData(d=>d?{...d,project:{...d.project,[key]:value}}:d)}
  function setRevenue<K extends keyof RevenueModel>(key:K,value:RevenueModel[K]){setData(d=>d?{...d,revenue:{...d.revenue,[key]:value}}:d)}
  async function saveProject(){setSaving(true);setError('');try{const r=await fetch(`/api/projects/${projectId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data!.project)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(v=>v?{...v,project:d.project}:v)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  async function saveRevenue(){setSaving(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/revenue`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data!.revenue)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(v=>v?{...v,revenue:d.revenue}:v)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  async function remove(kind:'items'|'costs',id:string){if(!confirm('Remove this line from the project?'))return;await fetch(`/api/${kind}/${id}`,{method:'DELETE'});load()}
  async function changeItemStatus(id:string,status:string){setData(current=>current?{...current,items:current.items.map(item=>item.id===id?{...item,status:status as ProjectItem['status']}:item)}:current);const response=await fetch(`/api/items/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!response.ok){const payload=await response.json();setError(payload.error);load()}}
  async function submitItem(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/projects/${projectId}/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setAddItem(false);load()}
  async function submitCost(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/projects/${projectId}/costs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return}setAddCost(false);load()}
  const e=economics!;
  return <>
    <Link href="/projects" style={{display:'inline-flex',alignItems:'center',gap:6,color:'#627169',fontSize:11,marginBottom:13}}><ArrowLeft size={14}/>Back to projects</Link>
    <section className="project-hero"><div><p className="eyebrow">{data.project.code} · {data.project.status}</p><h1>{data.project.name}</h1><p>{data.project.customer_name} · {data.project.location}</p></div><div style={{display:'flex',gap:30}}><div className="hero-stat"><span>System size</span><strong>{number(Number(data.project.capacity_kw),2)} kW</strong></div><div className="hero-stat"><span>Total modeled cost</span><strong>{money(e.totalProjectCost,true)}</strong></div></div></section>
    {error&&<div className="error-banner">{error}</div>}
    <div className="tabs">{tabs.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'tab active':'tab'} onClick={()=>setTab(id)}><span style={{display:'inline-flex',alignItems:'center',gap:7}}><Icon size={14}/>{label}</span></button>)}</div>

    {tab==='overview'&&<Overview data={data} e={e} setProject={setProject} save={saveProject} saving={saving}/>} 
    {tab==='inventory'&&<InventoryEditor data={data} e={e} add={()=>setAddItem(true)} remove={(id)=>remove('items',id)} changeStatus={changeItemStatus}/>} 
    {tab==='costs'&&<CostsByCategory data={data} e={e} add={()=>setAddCost(true)} remove={(id)=>remove('costs',id)}/>} 
    {tab==='economics'&&<><EconomicsView data={data} e={e} setProject={setProject} setRevenue={setRevenue} save={async()=>{await saveProject();await saveRevenue()}} saving={saving}/><BreakevenChart e={e}/></>} 
    {tab==='sharing'&&<RevenueSharing data={data} e={e} setRevenue={setRevenue} save={saveRevenue} saving={saving}/>} 

    {addItem&&<ItemModal data={data} close={()=>setAddItem(false)} submit={submitItem}/>} 
    {addCost&&<CostCategoryModal close={()=>setAddCost(false)} submit={submitCost}/>} 
  </>;
}

function Overview({data,e,setProject,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setProject:<K extends keyof Project>(k:K,v:Project[K])=>void;save:()=>void;saving:boolean}){
  const installationCosts=data.costs.filter(cost=>(cost.cost_category||'Installation')==='Installation').reduce((sum,cost)=>sum+Number(cost.amount),0);
  const maintenanceCosts=data.costs.filter(cost=>cost.cost_category==='Maintenance').reduce((sum,cost)=>sum+Number(cost.amount),0);
  const costChart=[{name:'Installation',value:e.equipmentCost+installationCosts},{name:'Maintenance',value:maintenanceCosts}];
  return <><div className="metric-grid"><Metric label="Project investment" value={money(e.totalProjectCost,true)} note={`${money(e.equipmentCost,true)} Materials`} icon={Banknote} hero/><Metric label="Year-one generation" value={`${number(e.yearOneGeneration/1000,1)} MWh`} note={`${number(Number(data.project.specific_yield_kwh_kw))} kWh/kW yield`} icon={Zap}/><Metric label="Customer net savings" value={money(e.customerNetSavings,true)} note="Year one after customer fee" icon={CircleDollarSign}/><Metric label="Platform payback" value={e.projectPaybackYears?`${e.projectPaybackYears} years`:'Beyond term'} note={`${number(e.roiPct,1)}% contract ROI`} icon={TrendingUp}/></div>
    <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Project assumptions</h2><p>Changes recalculate the model immediately</p></div><button className="button primary small" onClick={save} disabled={saving}><Save size={13}/>{saving?'Saving…':'Save assumptions'}</button></div><div className="assumption-grid"><Assumption label="System capacity (kW)" value={data.project.capacity_kw} onChange={v=>setProject('capacity_kw',v)}/><Assumption label="Annual customer load (kWh)" value={data.project.annual_usage_kwh} onChange={v=>setProject('annual_usage_kwh',v)}/><Assumption label="Electricity rate (MXN/kWh)" value={data.project.electricity_rate} step="0.01" onChange={v=>setProject('electricity_rate',v)}/><Assumption label="Specific yield (kWh/kW)" value={data.project.specific_yield_kwh_kw} onChange={v=>setProject('specific_yield_kwh_kw',v)}/><Assumption label="Utility escalation (%)" value={data.project.utility_escalation_pct} step="0.1" onChange={v=>setProject('utility_escalation_pct',v)}/><Assumption label="Module degradation (%)" value={data.project.degradation_pct} step="0.05" onChange={v=>setProject('degradation_pct',v)}/></div></section>
    <section className="card"><div className="card-header"><div><h2>Capital stack</h2><p>Current project cost composition</p></div></div><div className="chart-wrap" style={{height:250}}><ResponsiveContainer width="100%" height="100%"><BarChart data={costChart} layout="vertical" margin={{left:8,right:20}}><CartesianGrid stroke="#e8ede9" horizontal={false}/><XAxis type="number" tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" tick={{fontSize:10}} width={70} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="value" radius={[0,7,7,0]}>{costChart.map((_,i)=><Cell key={i} fill={i===0?'#143d2d':'#f4c75d'}/>)}</Bar></BarChart></ResponsiveContainer></div></section></div></>;
}

function Inventory({data,e,add,remove}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void}){
  return <section className="card"><div className="card-header"><div><h2>Bill of materials & sourcing</h2><p>{data.items.length} line items · {money(e.equipmentCost,true)} total equipment</p></div><button className="button primary small" onClick={add}><PackagePlus size={14}/>Add from catalog</button></div>{data.items.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Qty.</th><th>Unit cost</th><th>Extended</th><th>Supplier</th><th>Delivery</th><th>Status</th><th></th></tr></thead><tbody>{data.items.map(i=><tr key={i.id}><td><div className="table-title"><div><span className="project-code">{i.product_category} · {i.product_sku}</span><strong>{i.product_name}</strong><span>{i.product_model}</span></div></div></td><td>{number(Number(i.quantity),2)}</td><td>{money(Number(i.unit_price))}</td><td><strong>{money(Number(i.quantity)*Number(i.unit_price),true)}</strong></td><td>{i.supplier||'—'}</td><td>{i.expected_delivery?new Date(i.expected_delivery+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—'}</td><td><span className={`status ${i.status.replace(' ','-')}`}>{i.status}</span></td><td><button className="button ghost small" onClick={()=>remove(i.id)} aria-label="Remove"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty icon={Boxes} title="No products assigned" text="Choose products from the catalog to build this project's bill of materials."/>}</section>;
}

function InventoryEditor({data,e,add,remove,changeStatus}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void;changeStatus:(id:string,status:string)=>void}){
  const statuses=['Planned','Quoted','Ordered','In transit','Delivered','Installed'];
  return <section className="card">
    <div className="card-header"><div><h2>Bill of materials & sourcing</h2><p>{data.items.length} sourced product lines with delivery and fulfillment tracking</p></div><button className="button primary small" onClick={add}><PackagePlus size={14}/>Add from catalog</button></div>
    {data.items.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Qty.</th><th>Unit cost</th><th>Extended</th><th>Supplier</th><th>Delivery</th><th>Status</th><th></th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}>
      <td><div className="table-title"><div><span className="project-code">{item.product_category} · {item.product_sku}</span><strong>{item.product_name}</strong><span>{item.product_model}</span></div></div></td>
      <td>{number(Number(item.quantity),2)}</td><td>{money(Number(item.unit_price))}</td><td><strong>{money(Number(item.quantity)*Number(item.unit_price),true)}</strong></td><td>{item.supplier||'—'}</td>
      <td>{item.expected_delivery?formatWorkspaceDate(item.expected_delivery):'—'}</td>
      <td><select className="inline-select" aria-label={`Sourcing status for ${item.product_name}`} value={item.status} onChange={event=>changeStatus(item.id,event.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></td>
      <td><button className="button ghost small" onClick={()=>remove(item.id)} aria-label="Remove"><Trash2 size={14}/></button></td>
    </tr>)}</tbody><tfoot><tr className="bom-total-row"><td colSpan={3}><strong>Total bill of materials</strong></td><td><strong>{money(e.equipmentCost)}</strong><span>total cost</span></td><td colSpan={4}></td></tr></tfoot></table></div>:<Empty icon={Boxes} title="No products assigned" text="Choose products from the catalog to build this project's bill of materials."/>}
  </section>;
}

function Costs({data,e,add,remove}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void}){
  const grouped=Object.entries(data.costs.reduce<Record<string,number>>((a,c)=>{a[c.cost_type]=(a[c.cost_type]||0)+Number(c.amount);return a},{}));
  return <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Non-equipment project costs</h2><p>Installation, shipping, permits, engineering, and reserves</p></div><button className="button primary small" onClick={add}><Plus size={14}/>Add cost</button></div>{data.costs.length?<div className="table-wrap"><table className="data-table" style={{minWidth:600}}><thead><tr><th>Cost</th><th>Type</th><th>Amount</th><th></th></tr></thead><tbody>{data.costs.map(c=><tr key={c.id}><td><strong>{c.label}</strong>{c.notes&&<span style={{display:'block',fontSize:9,color:'#7a8780',marginTop:3}}>{c.notes}</span>}</td><td><span className="status">{c.cost_type}</span></td><td><strong>{money(Number(c.amount))}</strong></td><td><button className="button ghost small" onClick={()=>remove(c.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty icon={Banknote} title="No soft costs yet" text="Add installation, freight, permits and other project costs."/>}</section><section className="card"><div className="card-header"><div><h2>Cost summary</h2><p>Fully-loaded capital requirement</p></div></div><div className="mini-metrics"><div className="mini-metric"><span>Equipment</span><strong>{money(e.equipmentCost,true)}</strong></div><div className="mini-metric"><span>Other project costs</span><strong>{money(e.softCosts,true)}</strong></div><div className="mini-metric" style={{gridColumn:'1/-1',background:'#143d2d',color:'white'}}><span style={{color:'#a7c0b4'}}>Total project cost</span><strong>{money(e.totalProjectCost,true)}</strong></div></div><div style={{padding:'0 18px 18px'}}>{grouped.map(([type,value])=><div key={type} style={{display:'flex',justifyContent:'space-between',padding:'9px 0',borderBottom:'1px solid #edf1ee',fontSize:11}}><span style={{color:'#66736d'}}>{type}</span><strong>{money(value,true)}</strong></div>)}</div></section></div>;
}

function CostsByCategory({data,e,add,remove}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;add:()=>void;remove:(id:string)=>void}){
  const installation=data.costs.filter(cost=>(cost.cost_category||'Installation')==='Installation');
  const maintenance=data.costs.filter(cost=>cost.cost_category==='Maintenance');
  const installationServicesTotal=installation.reduce((sum,cost)=>sum+Number(cost.amount),0);
  const installationTotal=e.equipmentCost+installationServicesTotal;
  const maintenanceTotal=maintenance.reduce((sum,cost)=>sum+Number(cost.amount),0);
  return <>
    <div className="cost-category-heading"><div><h2>Installation & maintenance costs</h2><p>Separate upfront delivery costs from ongoing asset-care allowances.</p></div><button className="button primary small" onClick={add}><Plus size={14}/>Add cost</button></div>
    <div className="cost-category-grid">
      <CostBucket title="Installation" description="Materials, engineering, permits, freight and construction" icon={Banknote} costs={installation} total={installationTotal} materialsTotal={e.equipmentCost} remove={remove}/>
      <CostBucket title="Maintenance" description="Monitoring, cleaning, preventive and corrective care" icon={CalendarClock} costs={maintenance} total={maintenanceTotal} remove={remove}/>
    </div>
    <section className="card cost-total-card"><div className="mini-metrics" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="mini-metric"><span>Installation incl. Materials</span><strong>{money(installationTotal,true)}</strong></div><div className="mini-metric"><span>Maintenance</span><strong>{money(maintenanceTotal,true)}</strong></div><div className="mini-metric" style={{background:'#143d2d',color:'white'}}><span style={{color:'#a7c0b4'}}>Total project cost</span><strong>{money(e.totalProjectCost,true)}</strong></div></div></section>
  </>;
}

function CostBucket({title,description,icon:Icon,costs,total,materialsTotal,remove}:{title:string;description:string;icon:React.ElementType;costs:ProjectCost[];total:number;materialsTotal?:number;remove:(id:string)=>void}){
  const hasMaterials=materialsTotal!==undefined;
  return <section className="card cost-bucket"><div className="card-header"><div className="cost-bucket-title"><span className="metric-icon"><Icon size={16}/></span><div><h2>{title}</h2><p>{description}</p></div></div><strong>{money(total,true)}</strong></div>
    {(hasMaterials||costs.length)?<div className="table-wrap"><table className="data-table cost-table"><thead><tr><th>Cost</th><th>Type</th><th>Amount</th><th></th></tr></thead><tbody>{hasMaterials&&<tr className="materials-cost-row"><td><strong>Materials</strong><span className="cost-note">Automatically tallied from Products & sourcing</span></td><td><span className="status">Products & sourcing</span></td><td><strong>{money(materialsTotal)}</strong></td><td></td></tr>}{costs.map(cost=><tr key={cost.id}><td><strong>{cost.label}</strong>{cost.notes&&<span className="cost-note">{cost.notes}</span>}</td><td><span className="status">{cost.cost_type}</span></td><td><strong>{money(Number(cost.amount))}</strong></td><td><button className="button ghost small" onClick={()=>remove(cost.id)} aria-label={`Remove ${cost.label}`}><Trash2 size={14}/></button></td></tr>)}</tbody><tfoot><tr><td><strong>{title} subtotal</strong></td><td></td><td><strong>{money(total)}</strong></td><td></td></tr></tfoot></table></div>:<Empty icon={Icon} title={`No ${title.toLowerCase()} costs`} text={`Add the first ${title.toLowerCase()} cost to this project.`}/>}</section>;
}

function EconomicsView({data,e,setProject,setRevenue,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setProject:<K extends keyof Project>(k:K,v:Project[K])=>void;setRevenue:<K extends keyof RevenueModel>(k:K,v:RevenueModel[K])=>void;save:()=>void;saving:boolean}){
  return <><div className="metric-grid"><Metric label="Year-one bill avoided" value={money(e.yearOneBillSavings,true)} note={`${number(e.yearOneGeneration/1000,1)} MWh generated`} icon={Zap} hero/><Metric label="Customer annual fee" value={money(e.yearOneRevenue,true)} note={money(Number(data.revenue.monthly_customer_fee))+' monthly'} icon={CircleDollarSign}/><Metric label="Customer saves in year 1" value={money(e.customerNetSavings,true)} note={`${number(e.yearOneBillSavings?e.customerNetSavings/e.yearOneBillSavings*100:0,1)}% below avoided utility bill`} icon={Users}/><Metric label="Customer lifetime savings" value={money(e.customerLifetimeSavings,true)} note={`${data.revenue.contract_years}-year contract`} icon={TrendingUp}/></div>
    <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Customer value proposition</h2><p>Utility bill avoided, customer fee, and net savings</p></div></div><div className="chart-wrap" style={{height:360}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={e.series} margin={{top:5,right:20,left:8}}><CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tickFormatter={v=>`Y${v}`} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>`Year ${v}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/><Legend wrapperStyle={{fontSize:10}}/><Area type="monotone" dataKey="billSavings" name="Utility bill avoided" stroke="#5d83be" fill="#dfe9f7" strokeWidth={2}/><Area type="monotone" dataKey="customerFee" name="Customer fee" stroke="#143d2d" fill="#dcebe3" strokeWidth={2}/><Line type="monotone" dataKey="customerNetSavings" name="Customer net savings" stroke="#e2a82d" strokeWidth={3} dot={false}/></AreaChart></ResponsiveContainer></div></section>
    <section className="card"><div className="card-header"><div><h2>Commercial assumptions</h2><p>Adjust and see results immediately</p></div><button className="button primary small" onClick={save} disabled={saving}><Save size={13}/>{saving?'Saving…':'Save model'}</button></div><div className="assumption-grid" style={{gridTemplateColumns:'1fr 1fr'}}><Assumption label="Monthly customer fee (MXN)" value={data.revenue.monthly_customer_fee} onChange={v=>setRevenue('monthly_customer_fee',v)}/><Assumption label="Contract term (years)" value={data.revenue.contract_years} onChange={v=>setRevenue('contract_years',v)}/><Assumption label="Electricity rate (MXN/kWh)" value={data.project.electricity_rate} step="0.01" onChange={v=>setProject('electricity_rate',v)}/><Assumption label="Utility escalation (%)" value={data.project.utility_escalation_pct} step="0.1" onChange={v=>setProject('utility_escalation_pct',v)}/><Assumption label="Annual fee escalation (%)" value={data.revenue.annual_fee_escalation_pct} step="0.1" onChange={v=>setRevenue('annual_fee_escalation_pct',v)}/><Assumption label="Discount rate (%)" value={data.revenue.discount_rate_pct} step="0.1" onChange={v=>setRevenue('discount_rate_pct',v)}/></div></section></div></>;
}

function BreakevenChart({e}:{e:ReturnType<typeof calculateEconomics>}){
  const payback=e.projectPaybackYears;
  const series=[
    {year:0,cumulative:-e.totalProjectCost,negative:-e.totalProjectCost,positive:null as number|null},
    ...e.series.map(point=>({year:point.year,cumulative:point.cumulativePlatform,negative:point.cumulativePlatform<=0?point.cumulativePlatform:null,positive:point.cumulativePlatform>=0?point.cumulativePlatform:null})),
  ];
  if(payback!==null&&!Number.isInteger(payback))series.push({year:payback,cumulative:0,negative:0,positive:0});
  series.sort((a,b)=>a.year-b.year);
  const wholeYears=payback===null?0:Math.floor(payback);
  const months=payback===null?0:Math.round((payback-wholeYears)*12);
  const paybackLabel=payback===null?'Beyond contract term':`${wholeYears} yr${wholeYears===1?'':'s'}${months?` ${months} mo`:''}`;
  return <section className="card breakeven-card">
    <div className="card-header"><div><h2>Project break-even</h2><p>Cumulative Soluziomex cash flow after the full upfront project investment</p></div><span className={`status ${payback!==null?'Operating':''}`}>{payback!==null?`Break-even · year ${number(payback,1)}`:'No break-even in term'}</span></div>
    <div className="breakeven-layout">
      <div className="breakeven-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series} margin={{top:30,right:24,left:12,bottom:8}}>
        <defs><linearGradient id="lossArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#dc6158" stopOpacity={.16}/><stop offset="100%" stopColor="#dc6158" stopOpacity={.48}/></linearGradient><linearGradient id="profitArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3a9a68" stopOpacity={.36}/><stop offset="100%" stopColor="#3a9a68" stopOpacity={.08}/></linearGradient></defs>
        <CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis type="number" dataKey="year" domain={[0,'dataMax']} tickFormatter={value=>`Y${value}`} tick={{fontSize:9,fill:'#738078'}} axisLine={false} tickLine={false}/><YAxis tickFormatter={value=>money(value,true)} tick={{fontSize:9,fill:'#738078'}} axisLine={false} tickLine={false}/><Tooltip formatter={value=>money(Number(value))} labelFormatter={value=>Number(value)===0?'Initial investment':`Year ${number(Number(value),1)}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/>
        <ReferenceLine y={0} stroke="#293b33" strokeWidth={1.5} label={{value:'CASH BREAK-EVEN',position:'insideTopLeft',fill:'#53635b',fontSize:9}}/>
        {payback!==null&&<ReferenceLine x={payback} stroke="#3a9a68" strokeDasharray="4 4" label={{value:`PAYBACK ${number(payback,1)} YRS`,position:'top',fill:'#27774f',fontSize:10,fontWeight:700}}/>}
        <Area type="linear" dataKey="negative" name="Capital not yet recovered" stroke="#cf5148" strokeWidth={3} fill="url(#lossArea)" connectNulls={false}/><Area type="linear" dataKey="positive" name="Cumulative profit" stroke="#2d895c" strokeWidth={3} fill="url(#profitArea)" connectNulls={false}/>
      </AreaChart></ResponsiveContainer></div>
      <aside className="breakeven-summary"><p className="eyebrow">Capital recovery</p><span className="breakeven-label">Estimated payback</span><strong className="breakeven-value">{paybackLabel}</strong><span className="breakeven-month">{payback!==null?`Approximately month ${Math.round(payback*12)}`:'Increase the fee or reduce project cost'}</span><div className="breakeven-key"><div><i className="loss-dot"/><span>Red</span><strong>Recovering {money(e.totalProjectCost,true)} investment</strong></div><div><i className="profit-dot"/><span>Green</span><strong>Positive cumulative project cash</strong></div></div><div className="breakeven-stats"><div><span>Year-one platform cash</span><strong>{money(e.platformYearOne,true)}</strong></div><div><span>Contract ROI</span><strong>{number(e.roiPct,1)}%</strong></div></div></aside>
    </div>
  </section>;
}

function RevenueSharing({data,e,setRevenue,save,saving}:{data:WorkspaceData;e:ReturnType<typeof calculateEconomics>;setRevenue:<K extends keyof RevenueModel>(k:K,v:RevenueModel[K])=>void;save:()=>void;saving:boolean}){
  const total=Number(data.revenue.installer_share_pct)+Number(data.revenue.maintenance_reserve_pct)+Number(data.revenue.platform_share_pct);
  return <><div className="metric-grid"><Metric label="Installer year-one share" value={money(e.installerYearOne,true)} note={`${data.revenue.installer_share_pct}% of customer fees`} icon={Handshake} hero/><Metric label="Maintenance reserve" value={money(e.maintenanceYearOne,true)} note={`${data.revenue.maintenance_reserve_pct}% retained for asset care`} icon={CalendarClock}/><Metric label="Soluziomex year-one cash" value={money(e.platformYearOne,true)} note={`${data.revenue.platform_share_pct}% platform share`} icon={CircleDollarSign}/><Metric label="Platform NPV" value={money(e.npv,true)} note={`${data.revenue.discount_rate_pct}% discount rate`} icon={TrendingUp}/></div>
    <div className="section-grid"><section className="card"><div className="card-header"><div><h2>Aligned cash flow</h2><p>Annual distribution of customer revenue</p></div></div><div className="chart-wrap" style={{height:360}}><ResponsiveContainer width="100%" height="100%"><BarChart data={e.series} margin={{top:5,right:20,left:10}}><CartesianGrid stroke="#e7ece8" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tickFormatter={v=>`Y${v}`} tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>money(v,true)} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>`Year ${v}`} contentStyle={{borderRadius:10,border:'1px solid #e2e8e4',fontSize:10}}/><Legend wrapperStyle={{fontSize:10}}/><Bar dataKey="platform" name="Soluziomex" stackId="a" fill="#143d2d"/><Bar dataKey="maintenance" name="Maintenance reserve" stackId="a" fill="#77aa91"/><Bar dataKey="installer" name="Installer" stackId="a" fill="#f4c75d" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>
    <section className="card"><div className="card-header"><div><h2>Revenue split designer</h2><p>Long-term incentive alignment</p></div><button className="button primary small" onClick={save} disabled={saving||Math.abs(total-100)>.001}><Save size={13}/>{saving?'Saving…':'Save split'}</button></div><div className="split-bar"><span style={{width:`${data.revenue.installer_share_pct}%`}}/><span style={{width:`${data.revenue.maintenance_reserve_pct}%`}}/><span style={{width:`${data.revenue.platform_share_pct}%`}}/></div><div className="legend"><div>Installer<strong>{data.revenue.installer_share_pct}%</strong></div><div>Maintenance<strong>{data.revenue.maintenance_reserve_pct}%</strong></div><div>Soluziomex<strong>{data.revenue.platform_share_pct}%</strong></div></div><div className="assumption-grid" style={{gridTemplateColumns:'1fr 1fr'}}><Assumption label="Installer share (%)" value={data.revenue.installer_share_pct} step="0.5" onChange={v=>setRevenue('installer_share_pct',v)}/><Assumption label="Maintenance reserve (%)" value={data.revenue.maintenance_reserve_pct} step="0.5" onChange={v=>setRevenue('maintenance_reserve_pct',v)}/><Assumption label="Soluziomex share (%)" value={data.revenue.platform_share_pct} step="0.5" onChange={v=>setRevenue('platform_share_pct',v)}/><Assumption label="Monthly fee (MXN)" value={data.revenue.monthly_customer_fee} onChange={v=>setRevenue('monthly_customer_fee',v)}/></div><div style={{margin:'0 18px 18px',padding:11,borderRadius:9,background:Math.abs(total-100)<.001?'#eaf5ee':'#fff1ef',color:Math.abs(total-100)<.001?'#397255':'#a64840',fontSize:10,fontWeight:700}}>Total allocation: {number(total,1)}% {Math.abs(total-100)<.001?'· ready to save':'· shares must equal 100%'}</div></section></div>
    <section className="card" style={{marginTop:18}}><div className="card-header"><div><h2>Stakeholder outcomes</h2><p>Nominal distributions over the full {data.revenue.contract_years}-year contract</p></div></div><div className="mini-metrics" style={{gridTemplateColumns:'repeat(4,1fr)'}}><div className="mini-metric"><span>Total customer fees</span><strong>{money(e.contractRevenue,true)}</strong></div><div className="mini-metric"><span>Installer lifetime income</span><strong>{money(e.contractRevenue*Number(data.revenue.installer_share_pct)/100,true)}</strong></div><div className="mini-metric"><span>Maintenance funded</span><strong>{money(e.contractRevenue*Number(data.revenue.maintenance_reserve_pct)/100,true)}</strong></div><div className="mini-metric"><span>Soluziomex gross cash</span><strong>{money(e.contractPlatformCash,true)}</strong></div></div></section></>;
}

function Metric({label,value,note,icon:Icon,hero=false}:{label:string;value:string;note:string;icon:React.ElementType;hero?:boolean}){return <div className={`metric-card ${hero?'hero':''}`}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon size={16}/></span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>}
function Assumption({label,value,onChange,step='1'}:{label:string;value:string|number;onChange:(v:number)=>void;step?:string}){return <div className="assumption"><label>{label}</label><input type="number" step={step} value={Number(value)} onChange={ev=>onChange(Number(ev.target.value))}/></div>}
function Empty({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="empty-state"><Icon size={30}/><h3>{title}</h3><p>{text}</p></div>}

function ItemModal({data,close,submit}:{data:WorkspaceData;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){
  const[selected,setSelected]=useState(data.products[0]?.id||'');const product=data.products.find(p=>p.id===selected);
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Project sourcing</p><h2>Add product to bill of materials</h2></div><button type="button" className="button ghost small" onClick={close}>×</button></div><div className="modal-body"><div className="form-grid"><div className="form-field full"><label>Catalog product</label><select name="product_id" value={selected} onChange={e=>setSelected(e.target.value)}>{data.products.map(p=><option key={p.id} value={p.id}>{p.category} · {p.name} · {money(Number(p.unit_cost))}</option>)}</select></div><Field name="quantity" label="Quantity" type="number" step="0.01" defaultValue="1" required/><Field key={product?.id} name="unit_price" label="Project unit price (MXN)" type="number" step="0.01" defaultValue={product?.unit_cost||0}/><Field name="supplier" label="Supplier" placeholder="Supplier name"/><Field name="expected_delivery" label="Expected delivery" type="date"/><Select name="status" label="Status" options={['Planned','Quoted','Ordered','In transit','Delivered','Installed']}/><Field name="notes" label="Notes" placeholder="Quote or logistics notes"/></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Add product</button></div></form></div>;
}
function CostModal({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Project budget</p><h2>Add a project cost</h2></div><button type="button" className="button ghost small" onClick={close}>×</button></div><div className="modal-body"><div className="form-grid"><Select name="cost_type" label="Cost type" options={['Installation','Logistics','Permits','Engineering','Interconnection','Insurance','Financing','Contingency','Other']}/><Field name="label" label="Description" placeholder="Mechanical installation labor" required/><Field name="amount" label="Amount (MXN)" type="number" step="0.01" required/><Field name="notes" label="Notes" placeholder="Quote, assumptions, exclusions…"/></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Add cost</button></div></form></div>}
function CostCategoryModal({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){const[category,setCategory]=useState<'Installation'|'Maintenance'>('Installation');const types=category==='Installation'?['Labor','Logistics','Permits','Engineering','Interconnection','Insurance','Financing','Contingency','Other']:['Preventive maintenance','Corrective maintenance','Monitoring','Cleaning','Inspection','Replacement reserve','Insurance','Other'];return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Project budget</p><h2>Add a project cost</h2></div><button type="button" className="button ghost small" onClick={close}>×</button></div><div className="modal-body"><div className="form-grid"><div className="form-field"><label>Cost category</label><select name="cost_category" value={category} onChange={event=>setCategory(event.target.value as 'Installation'|'Maintenance')}><option>Installation</option><option>Maintenance</option></select></div><Select key={category} name="cost_type" label="Cost type" options={types}/><Field name="label" label="Description" placeholder={category==='Installation'?'Mechanical installation labor':'Annual preventive maintenance'} required/><Field name="amount" label="Amount (MXN)" type="number" step="0.01" required/><div className="form-field full"><label>Notes</label><textarea name="notes" placeholder="Quote, assumptions, frequency, exclusions…"/></div></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Add {category.toLowerCase()} cost</button></div></form></div>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...rest}=props;return <div className="form-field"><label>{label}</label><input {...rest}/></div>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <div className="form-field"><label>{label}</label><select name={name}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function formatWorkspaceDate(value:string){const parsed=new Date(value.length===10?`${value}T00:00:00Z`:value);return parsed.toLocaleDateString('en-US',{timeZone:'UTC',month:'short',day:'numeric'})}
